pkg:
  - apache2

apache:
  root: /var/www
  log_dir: /var/log/apache2
  email: webmaster@localhost
  interface: '<public IP>'
  http_port: 80
  websites:
          - { name: 'sportz', log_level: 'info ssl:warn', server: { name: 'example2.com', alias: 'www.example2.com' }, vhost: { name: 'example2', ip: '*', port: 80 }, tarball: 'sportz.zip' }
          - { name: 'industrie', log_level: 'info ssl:warn', server: { name: 'example3.com', alias: 'www.example3.com' }, vhost: { name: 'example3', ip: '*', port: 80 }, tarball: 'industrie.zip' }
